// Code generated by protoc-gen-go. DO NOT EDIT.
// source: http.proto

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	http.proto

It has these top-level messages:
	HTTPOption
	HTTPJob
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HTTPOption struct {
	Url string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	// GET, POST, PUT, DELETE, PATCH ..., default GET
	Method string `protobuf:"bytes,2,opt,name=method" json:"method,omitempty"`
	// custom headers
	Headers map[string]string `protobuf:"bytes,3,rep,name=headers" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// random user-agent
	RandUA      bool  `protobuf:"varint,4,opt,name=randUA" json:"randUA,omitempty"`
	UseProxy    bool  `protobuf:"varint,5,opt,name=useProxy" json:"useProxy,omitempty"`
	Goroutine   int64 `protobuf:"varint,6,opt,name=goroutine" json:"goroutine,omitempty"`
	ClientCount int64 `protobuf:"varint,7,opt,name=clientCount" json:"clientCount,omitempty"`
}

func (m *HTTPOption) Reset()                    { *m = HTTPOption{} }
func (m *HTTPOption) String() string            { return proto.CompactTextString(m) }
func (*HTTPOption) ProtoMessage()               {}
func (*HTTPOption) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HTTPOption) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *HTTPOption) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *HTTPOption) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *HTTPOption) GetRandUA() bool {
	if m != nil {
		return m.RandUA
	}
	return false
}

func (m *HTTPOption) GetUseProxy() bool {
	if m != nil {
		return m.UseProxy
	}
	return false
}

func (m *HTTPOption) GetGoroutine() int64 {
	if m != nil {
		return m.Goroutine
	}
	return 0
}

func (m *HTTPOption) GetClientCount() int64 {
	if m != nil {
		return m.ClientCount
	}
	return 0
}

type HTTPJob struct {
	Uuid   string      `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Option *HTTPOption `protobuf:"bytes,2,opt,name=option" json:"option,omitempty"`
}

func (m *HTTPJob) Reset()                    { *m = HTTPJob{} }
func (m *HTTPJob) String() string            { return proto.CompactTextString(m) }
func (*HTTPJob) ProtoMessage()               {}
func (*HTTPJob) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HTTPJob) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *HTTPJob) GetOption() *HTTPOption {
	if m != nil {
		return m.Option
	}
	return nil
}

func init() {
	proto.RegisterType((*HTTPOption)(nil), "ckeyer.com.attack.protos.HTTPOption")
	proto.RegisterType((*HTTPJob)(nil), "ckeyer.com.attack.protos.HTTPJob")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for HTTPAttacker service

type HTTPAttackerClient interface {
	StartHTTP(ctx context.Context, in *HTTPOption, opts ...grpc.CallOption) (*HTTPJob, error)
	StopHTTP(ctx context.Context, in *HTTPJob, opts ...grpc.CallOption) (*HTTPJob, error)
}

type hTTPAttackerClient struct {
	cc *grpc.ClientConn
}

func NewHTTPAttackerClient(cc *grpc.ClientConn) HTTPAttackerClient {
	return &hTTPAttackerClient{cc}
}

func (c *hTTPAttackerClient) StartHTTP(ctx context.Context, in *HTTPOption, opts ...grpc.CallOption) (*HTTPJob, error) {
	out := new(HTTPJob)
	err := grpc.Invoke(ctx, "/ckeyer.com.attack.protos.HTTPAttacker/StartHTTP", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hTTPAttackerClient) StopHTTP(ctx context.Context, in *HTTPJob, opts ...grpc.CallOption) (*HTTPJob, error) {
	out := new(HTTPJob)
	err := grpc.Invoke(ctx, "/ckeyer.com.attack.protos.HTTPAttacker/StopHTTP", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HTTPAttacker service

type HTTPAttackerServer interface {
	StartHTTP(context.Context, *HTTPOption) (*HTTPJob, error)
	StopHTTP(context.Context, *HTTPJob) (*HTTPJob, error)
}

func RegisterHTTPAttackerServer(s *grpc.Server, srv HTTPAttackerServer) {
	s.RegisterService(&_HTTPAttacker_serviceDesc, srv)
}

func _HTTPAttacker_StartHTTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HTTPOption)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPAttackerServer).StartHTTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ckeyer.com.attack.protos.HTTPAttacker/StartHTTP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPAttackerServer).StartHTTP(ctx, req.(*HTTPOption))
	}
	return interceptor(ctx, in, info, handler)
}

func _HTTPAttacker_StopHTTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HTTPJob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPAttackerServer).StopHTTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ckeyer.com.attack.protos.HTTPAttacker/StopHTTP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPAttackerServer).StopHTTP(ctx, req.(*HTTPJob))
	}
	return interceptor(ctx, in, info, handler)
}

var _HTTPAttacker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ckeyer.com.attack.protos.HTTPAttacker",
	HandlerType: (*HTTPAttackerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartHTTP",
			Handler:    _HTTPAttacker_StartHTTP_Handler,
		},
		{
			MethodName: "StopHTTP",
			Handler:    _HTTPAttacker_StopHTTP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "http.proto",
}

func init() { proto.RegisterFile("http.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x50, 0xb1, 0x6e, 0xe2, 0x40,
	0x14, 0x3c, 0x63, 0x30, 0xe6, 0x41, 0x71, 0x5a, 0x9d, 0x4e, 0x2b, 0x8b, 0xc2, 0x87, 0xae, 0x70,
	0x65, 0x74, 0x5c, 0x13, 0xa1, 0x34, 0x24, 0x8a, 0x84, 0x48, 0x11, 0x64, 0x48, 0x8a, 0xa4, 0x5a,
	0xec, 0x15, 0x58, 0x36, 0xfb, 0xac, 0xf5, 0x3a, 0x8a, 0xbf, 0x2b, 0x5d, 0xbe, 0x2e, 0xf2, 0xda,
	0x04, 0x9a, 0x24, 0x54, 0xde, 0x99, 0x79, 0x33, 0xef, 0x8d, 0x01, 0x76, 0x4a, 0x65, 0x7e, 0x26,
	0x51, 0x21, 0xa1, 0x61, 0xc2, 0x4b, 0x2e, 0xfd, 0x10, 0xf7, 0x3e, 0x53, 0x8a, 0x85, 0x49, 0x2d,
	0xe4, 0xce, 0x70, 0x8b, 0xb8, 0x4d, 0xf9, 0x98, 0x65, 0xf1, 0x98, 0x09, 0x81, 0x8a, 0xa9, 0x18,
	0x45, 0x5e, 0xcb, 0xa3, 0xd7, 0x16, 0xc0, 0x7c, 0xbd, 0x5e, 0xde, 0x65, 0x15, 0x4b, 0x7e, 0x82,
	0x59, 0xc8, 0x94, 0x1a, 0xae, 0xe1, 0xf5, 0x82, 0xea, 0x49, 0x7e, 0x83, 0xb5, 0xe7, 0x6a, 0x87,
	0x11, 0x6d, 0x69, 0xb2, 0x41, 0xe4, 0x16, 0xba, 0x3b, 0xce, 0x22, 0x2e, 0x73, 0x6a, 0xba, 0xa6,
	0xd7, 0x9f, 0xfc, 0xf3, 0x3f, 0x3b, 0xc1, 0x3f, 0x2e, 0xf0, 0xe7, 0xb5, 0xe7, 0x46, 0x28, 0x59,
	0x06, 0x87, 0x84, 0x6a, 0x89, 0x64, 0x22, 0xba, 0x9f, 0xd1, 0xb6, 0x6b, 0x78, 0x76, 0xd0, 0x20,
	0xe2, 0x80, 0x5d, 0xe4, 0x7c, 0x29, 0xf1, 0xa5, 0xa4, 0x1d, 0xad, 0x7c, 0x60, 0x32, 0x84, 0xde,
	0x16, 0x25, 0x16, 0x2a, 0x16, 0x9c, 0x5a, 0xae, 0xe1, 0x99, 0xc1, 0x91, 0x20, 0x2e, 0xf4, 0xc3,
	0x34, 0xe6, 0x42, 0x5d, 0x63, 0x21, 0x14, 0xed, 0x6a, 0xfd, 0x94, 0x72, 0xa6, 0x30, 0x38, 0x3d,
	0xa6, 0xaa, 0x9e, 0xf0, 0xf2, 0x50, 0x3d, 0xe1, 0x25, 0xf9, 0x05, 0x9d, 0x67, 0x96, 0x16, 0xbc,
	0x69, 0x5e, 0x83, 0x69, 0xeb, 0xc2, 0x18, 0x3d, 0x41, 0xb7, 0xea, 0xb4, 0xc0, 0x0d, 0x21, 0xd0,
	0x2e, 0x8a, 0x38, 0x6a, 0x7c, 0xfa, 0x4d, 0x2e, 0xc1, 0x42, 0x5d, 0x57, 0x3b, 0xfb, 0x93, 0xbf,
	0xe7, 0xfc, 0x9a, 0xa0, 0xf1, 0x4c, 0xde, 0x0c, 0x18, 0x54, 0xf4, 0x4c, 0x0f, 0x72, 0x49, 0x1e,
	0xa0, 0xb7, 0x52, 0x4c, 0xaa, 0x8a, 0x24, 0x67, 0x65, 0x39, 0x7f, 0xbe, 0x9e, 0x5a, 0xe0, 0x66,
	0xf4, 0x83, 0x04, 0x60, 0xaf, 0x14, 0x66, 0x3a, 0xf6, 0x7b, 0xc3, 0x59, 0x99, 0x57, 0xf6, 0xa3,
	0x55, 0x73, 0x9b, 0xfa, 0xfb, 0xff, 0x3d, 0x00, 0x00, 0xff, 0xff, 0x22, 0xd7, 0xdf, 0xa0, 0xa6,
	0x02, 0x00, 0x00,
}
